In [66]:
import os
import pandas as pd

### Combine the DF

In [67]:
# Directory containing the CSV files
folder_path = 'College_Player_Season_Data'

# List to store dataframes
df_list = []

# Iterate through all CSV files in the folder
for year in range(2010, 2026):
    file_name = f'trank_data_{year}.csv'
    file_path = os.path.join(folder_path, file_name)
    
    if os.path.exists(file_path):
        # Load the CSV file into a DataFrame
        df = pd.read_csv(file_path)
        
        # Add a 'year' column
        df['year'] = year
        
        # Append to the list
        df_list.append(df)

# Combine all dataframes
combined_df = pd.concat(df_list, ignore_index=True)

In [68]:
# reorder the df
column_order = [
    # Player and Team Information
    'player_name', 'team', 'conf', 'yr', 'ht', 'num', 'pid', 'type', 'pos_class',
    # Performance Metrics
    'GP', 'Min_per', 'ORtg', 'usg', 'eFG', 'TS_per', 'ORB_per', 'DRB_per', 
    'AST_per', 'TO_per', 'FTM', 'FTA', 'FT_per', 'twoPM', 'twoPA', 'twoP_per', 
    'TPM', 'TPA', 'TP_per', 'blk_per', 'stl_per', 'ftr',
    # Advanced Metrics
    'porpag', 'adjoe', 'pfr', 'Rec Rank', 'ast/tov', 'rimmade', 'rimmade+rimmiss', 
    'midmade', 'midmade+midmiss', 'rimmade/(rimmade+rimmiss)', 
    'midmade/(midmade+midmiss)', 'dunksmade', 'dunksmiss+dunksmade', 
    'dunksmade/(dunksmade+dunksmiss)',
    # Defensive Metrics
    'pick', 'drtg', 'adrtg', 'dporpag', 'stops',
    # Box Plus-Minus Metrics
    'bpm', 'obpm', 'dbpm', 'gbpm', 'ogbpm', 'dgbpm',
    # Counting Stats
    'mp', 'oreb', 'dreb', 'treb', 'ast', 'stl', 'blk', 'pts',
    # Metadata
    'year'
]

# Rearrange the DataFrame columns
combined_df = combined_df[column_order]

In [69]:
pd.options.display.max_columns = None
combined_df.head()

,player_name,team,conf,yr,ht,num,pid,type,pos_class,GP,Min_per,ORtg,usg,eFG,TS_per,ORB_per,DRB_per,AST_per,TO_per,FTM,FTA,FT_per,twoPM,twoPA,twoP_per,TPM,TPA,TP_per,blk_per,stl_per,ftr,porpag,adjoe,pfr,Rec Rank,ast/tov,rimmade,rimmade+rimmiss,midmade,midmade+midmiss,rimmade/(rimmade+rimmiss),midmade/(midmade+midmiss),dunksmade,dunksmiss+dunksmade,dunksmade/(dunksmade+dunksmiss),pick,drtg,adrtg,dporpag,stops,bpm,obpm,dbpm,gbpm,ogbpm,dgbpm,mp,oreb,dreb,treb,ast,stl,blk,pts,year
0,Pooh Williams,Utah St.,WAC,Jr,3-Jun,5,3,NaN,Combo G,32,64.0,108.3,18.1,53.0,53.33,2.3,5.9,14.6,14.1,33,62,0.532,70,134,0.522,36,100,0.360,0.9,1.4,26.5,1.801170,104.80200,2.7,NaN,1.999909,48.0,75.0,22.0,59.0,0.6400,0.3729,6.0,7.0,0.8571,NaN,100.875,98.5761,2.636630,124.827000,2.282520,2.426980,-0.144461,1.06223,0.78596,0.276271,27.3125,0.4688,1.3750,1.8438,2.1875,0.5938,0.2188,8.7812,2010
1,Nick Rodgers,Butler,Horz,Sr,2-Jun,14,11,NaN,Pure PG,11,1.0,121.1,16.8,75.0,75.00,0.0,0.0,15.8,24.8,0,0,0.000,0,1,0.000,2,3,0.667,0.0,0.0,0.0,0.145670,116.50800,8.0,NaN,1.000000,0.0,0.0,0.0,1.0,NaN,0.0000,0.0,0.0,NaN,NaN,102.878,101.9380,0.116247,1.586250,-3.890510,0.869061,-4.759570,1.80259,2.31746,-0.514877,1.3636,0.0000,0.0000,0.0000,0.0909,0.0000,0.0000,0.5455,2010
2,Dana Smith,Longwood,ind,Sr,5-Jun,22,13,NaN,Wing F,27,81.8,99.8,27.7,49.9,53.76,6.9,17.6,15.6,18.6,123,187,0.658,126,261,0.483,33,91,0.363,1.4,1.4,53.1,2.553470,108.22400,4.3,NaN,0.773810,82.0,134.0,44.0,127.0,0.6119,0.3465,3.0,4.0,0.7500,NaN,106.301,110.6310,1.801420,168.428000,-0.441037,1.107340,-1.548380,-0.11805,1.94935,-2.067400,32.7037,2.1481,4.9259,7.0741,2.4074,0.8148,0.4815,17.5556,2010
3,Matt Beck,Fordham,A10,Sr,Jun-00,20,15,NaN,Combo G,7,1.3,220.8,0.7,0.0,0.00,0.0,0.0,11.6,0.0,0,0,0.000,0,0,0.000,0,0,0.000,0.0,0.0,0.0,0.682753,177.54400,0.0,NaN,1.000300,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,119.570,116.2110,0.076539,1.356340,-10.067400,-4.984850,-5.082530,-7.95351,-4.64808,-3.305430,2.1429,0.0000,0.0000,0.0000,0.1429,0.0000,0.0000,0.0000,2010
4,Alex Hornat,Connecticut,BE,Sr,5-Jun,22,25,NaN,PF/C,2,0.2,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0,0,0.000,0,0,0.000,0,0,0.000,0.0,0.0,0.0,-0.486059,-7.66032,0.0,NaN,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,111.392,108.1570,0.095503,0.241481,-2.157200,-1.666500,-0.490701,-2.53318,-1.55686,-0.976320,1.5000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,2010

In [70]:
combined_df.describe()

,pid,GP,Min_per,ORtg,usg,eFG,TS_per,ORB_per,DRB_per,AST_per,TO_per,FTM,FTA,FT_per,twoPM,twoPA,twoP_per,TPM,TPA,TP_per,blk_per,stl_per,ftr,porpag,adjoe,pfr,Rec Rank,ast/tov,rimmade,rimmade+rimmiss,midmade,midmade+midmiss,rimmade/(rimmade+rimmiss),midmade/(midmade+midmiss),dunksmade,dunksmiss+dunksmade,dunksmade/(dunksmade+dunksmiss),pick,drtg,adrtg,dporpag,stops,bpm,obpm,dbpm,gbpm,ogbpm,dgbpm,mp,oreb,dreb,treb,ast,stl,blk,pts,year
count,7.658100e+04,76581.000000,76581.000000,76581.000000,76581.000000,76581.000000,76581.000000,76581.000000,76581.00000,76581.000000,76581.000000,76581.000000,76581.000000,76581.000000,76581.000000,76581.000000,76581.000000,76581.000000,76581.000000,76581.000000,76581.000000,76581.000000,76581.000000,76581.000000,76581.000000,76581.000000,22309.000000,76580.000000,74096.000000,74096.000000,74096.000000,74096.000000,68987.000000,68257.000000,74096.000000,74096.00000,38265.000000,1608.000000,76542.000000,76542.000000,76542.000000,76542.000000,76542.000000,76542.000000,76542.000000,76542.000000,76542.000000,76542.000000,76580.000000,76580.000000,76580.000000,76580.000000,76580.000000,76580.000000,76580.000000,76580.000000,76581.000000
mean,4.657401e+04,22.589089,36.810975,92.928558,18.100897,44.802352,47.833047,5.420385,12.79031,10.663469,19.509808,31.307883,44.452619,0.579700,40.330813,82.181533,0.431171,15.705945,45.927632,0.231883,1.868904,1.715304,35.828742,0.745805,90.258452,4.151534,55.363199,0.936264,27.757693,46.786007,13.849074,37.980296,0.561928,0.331038,3.883489,4.38527,0.858121,33.218905,103.842723,104.066716,1.440792,80.492854,-2.554717,-1.904132,-0.650585,-2.540053,-2.107459,-0.432594,16.917808,0.752248,1.917468,2.669716,1.078781,0.534368,0.280895,5.832211,2017.641974
std,2.729334e+04,10.246471,28.060444,31.808410,6.292950,18.744921,17.972158,8.623139,10.43407,9.217389,12.102462,35.532463,47.564618,0.276989,43.004922,83.323195,0.199426,21.231619,57.343785,0.189352,5.270151,2.090100,36.260633,1.299501,31.753116,4.792024,27.015348,0.757521,29.973131,47.662646,17.144951,42.826202,0.191378,0.177960,7.982915,8.78245,0.233650,16.427945,9.795011,10.740394,1.066969,64.584267,7.523944,5.179188,4.162819,8.664122,6.492304,3.373128,10.563519,0.721610,1.483040,2.079617,1.161797,0.467612,0.405250,4.930799,4.624714
min,2.000000e+00,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-7.248940,-39.479800,0.000000,0.200000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,1.000000,-1330.060000,-1292.020000,-0.792400,0.018426,-102.186000,-92.474400,-57.459400,-426.137000,-335.447000,-100.957000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2010.000000
25%,2.534800e+04,15.000000,8.800000,85.100000,14.400000,40.400000,44.120000,1.700000,8.50000,4.600000,14.000000,3.000000,6.000000,0.500000,5.000000,12.000000,0.376000,0.000000,1.000000,0.000000,0.000000,0.900000,18.100000,-0.175585,80.546000,2.700000,34.200000,0.431865,4.000000,8.000000,1.000000,5.000000,0.500000,0.250000,0.000000,0.00000,0.800000,20.000000,99.520675,98.610550,0.521818,17.944475,-5.363457,-3.932437,-2.304440,-5.342880,-4.383970,-1.722322,7.324625,0.222200,0.722200,1.000000,0.240000,0.166700,0.000000,1.656200,2014.000000
50%,4.409100e+04,27.000000,35.200000,98.200000,18.100000,48.000000,51.110000,4.100000,12.00000,8.900000,18.400000,19.000000,29.000000,0.667000,26.000000,56.000000,0.466000,5.000000,20.000000,0.280000,0.900000,1.500000,31.000000,0.383568,95.732400,3.600000,58.400000,0.836717,18.000000,32.000000,7.000000,23.000000,0.577800,0.338700,0.000000,1.00000,0.980000,34.000000,104.161000,104.412500,1.271365,73.343050,-1.807560,-1.305730,-0.593253,-1.753890,-1.548970,-0.303760,16.656200,0.533300,1.666700,2.285700,0.689700,0.433300,0.138900,4.580600,2018.000000
75%,7.127000e+04,31.000000,61.700000,107.900000,21.800000,53.700000,56.430000,7.900000,16.20000,14.800000,23.700000,48.000000,68.000000,0.763000,63.000000,130.000000,0.533000,25.000000,75.000000,0.357000,2.500000,2.200000,45.800000,1.440840,107.559000,5.000000,78.400000,1.285733,42.000000,72.000000,20.000000,57.000000,0.666700,0.414600,4.000000,5.00000,1.000000,48.000000,108.816000,109.933000,2.183508,131.999000,1.398825,1.001732,1.103093,1.416317,0.969808,1.086145,26.242400,1.080000,2.800000,3.838700,1.541700,0.800000,0.366700,9.125000,2022.000000
max,2.450496e+06,41.000000,98.700000,300.000000,50.000000,150.000000,150.000000,1576.600000,1385.00000,100.000000,100.000000,310.000000,436.000000,1.000000,335.000000,678.000000,1.000000,155.000000,394.000000,1.000000,1072.000000,128.300000,1000.000000,8.520130,337.258000,720.000000,100.000000,16.000000,247.000000,358.000000,222.000000,532.000000,1.000000,1.000000,122.000000,132.00000,1.000000,60.000000,131.461000,158.792000,5.693920,360.572000,685.313000,161.995000,523.319000,269.508000,225.485000,98.164200,50.000000,5.933300,11.545500,15.117600,10.125000,4.000000,5.258100,30.090900,2025.000000

### Clean the data

In [71]:
# ht is in "Jun-3", convert it into CM
def convert_height(ht):
    feet_map = {'Jun': 6, 'Jul': 7, 'May': 5,'Apr': 4}
    if isinstance(ht, str):
        if "'" in ht:  # Case for heights like 6'4
            parts = ht.split("'")
            if len(parts) == 2 and parts[0].isdigit() and parts[1].isdigit():
                feet = int(parts[0])  # Feet part
                inches = int(parts[1])  # Inches part
                return round((feet * 30.48) + (inches * 2.54), 2)
        
        parts = ht.split('-')
        if len(parts) == 2:
            try:
                if not parts[0].isdigit():  # First part is a month name
                    parts[0] = str(feet_map.get(parts[0], parts[0]))  # Replace month name with number if found
                
                if not parts[1].isdigit():  # Second part is a month name
                    parts[1] = str(feet_map.get(parts[1], parts[1]))
                    
                # Check if any part is non-numeric (string), in that case treat it as feet
                if not parts[0].isdigit() and parts[1].isdigit():  # First part is non-numeric, treat as feet
                    feet = int(parts[1])  # Second part is inches
                    inches = int(parts[0])  # First part is feet
                elif not parts[1].isdigit() and parts[0].isdigit():  # Second part is non-numeric, treat as feet
                    feet = int(parts[0])  # First part is feet
                    inches = int(parts[1])  # Second part is inches
                else:
                    # If both parts are numeric, the first part is feet
                    feet = int(parts[0])
                    inches = int(parts[1])
                
                return round((feet * 30.48) + (inches * 2.54), 2)
            except ValueError:
                return None
    return None  # Return None if the format is invalid

# Apply the function to the 'ht' column
combined_df['ht'] = combined_df['ht'].apply(convert_height)

In [72]:
combined_df.to_csv('combined_data.csv', index=False)

## Aggregate combined data to player level

- Challenge 1: players with the same name. We thought player id (PID) would be unique but we found multiple names mapping to the same PID.
- Thus we will combine player and team as identification. This seems valid as only 0.09% of the team + name combination has more than 1 player id. 
- We also want to filter this data
    - Min_per: indicates % of minute played, ranges fro 0 - 100. We do not want to count the player performance if they play less than 10% of the game
    - There could also be data issue. We want to clean up data where rimmade+rimmiss, midmade+midmiss, dunksmiss+dunksmade are all nan or zero (aka. no effective player data)

In [130]:
combined_df_filtered = combined_df[
    ~(
        (combined_df['rimmade+rimmiss'].isna() | (combined_df['rimmade+rimmiss'] == 0)) &  # Condition 1
        (combined_df['midmade+midmiss'].isna() | (combined_df['midmade+midmiss'] == 0)) &  # Condition 2
        (combined_df['dunksmiss+dunksmade'].isna() | (combined_df['dunksmiss+dunksmade'] == 0))  # Condition 3
    )
]
combined_df_filtered = combined_df_filtered[combined_df_filtered['Min_per']>=10]
print(f'percentage filtered: {(1-combined_df_filtered.shape[0]/combined_df.shape[0]):0.2%}')

percentage filtered: 26.28%

In [131]:
combined_df_filtered.head()

,player_name,team,conf,yr,ht,num,pid,type,pos_class,GP,Min_per,ORtg,usg,eFG,TS_per,ORB_per,DRB_per,AST_per,TO_per,FTM,FTA,FT_per,twoPM,twoPA,twoP_per,TPM,TPA,TP_per,blk_per,stl_per,ftr,porpag,adjoe,pfr,Rec Rank,ast/tov,rimmade,rimmade+rimmiss,midmade,midmade+midmiss,rimmade/(rimmade+rimmiss),midmade/(midmade+midmiss),dunksmade,dunksmiss+dunksmade,dunksmade/(dunksmade+dunksmiss),pick,drtg,adrtg,dporpag,stops,bpm,obpm,dbpm,gbpm,ogbpm,dgbpm,mp,oreb,dreb,treb,ast,stl,blk,pts,year
0,Pooh Williams,Utah St.,WAC,Jr,106.68,5,3,NaN,Combo G,32,64.0,108.3,18.1,53.0,53.33,2.3,5.9,14.6,14.1,33,62,0.532,70,134,0.522,36,100,0.360,0.9,1.4,26.5,1.801170,104.8020,2.7,NaN,1.999909,48.0,75.0,22.0,59.0,0.6400,0.3729,6.0,7.0,0.8571,NaN,100.8750,98.5761,2.63663,124.8270,2.282520,2.42698,-0.144461,1.062230,0.785960,0.276271,27.3125,0.4688,1.3750,1.8438,2.1875,0.5938,0.2188,8.7812,2010
2,Dana Smith,Longwood,ind,Sr,167.64,22,13,NaN,Wing F,27,81.8,99.8,27.7,49.9,53.76,6.9,17.6,15.6,18.6,123,187,0.658,126,261,0.483,33,91,0.363,1.4,1.4,53.1,2.553470,108.2240,4.3,NaN,0.773810,82.0,134.0,44.0,127.0,0.6119,0.3465,3.0,4.0,0.7500,NaN,106.3010,110.6310,1.80142,168.4280,-0.441037,1.10734,-1.548380,-0.118050,1.949350,-2.067400,32.7037,2.1481,4.9259,7.0741,2.4074,0.8148,0.4815,17.5556,2010
5,Carlos Strong,Boston University,AE,Sr,106.68,22,32,"Portland, ME",Combo G,35,76.2,118.1,16.4,58.8,60.93,4.7,11.5,12.3,15.1,73,107,0.682,65,136,0.478,59,125,0.472,1.4,3.1,41.0,2.758120,111.8110,3.5,3.2,1.340383,47.0,78.0,19.0,58.0,0.6026,0.3276,13.0,15.0,0.8667,NaN,95.9093,98.0859,3.00456,215.8570,6.077490,3.66533,2.412160,5.253060,2.914710,2.338340,30.6857,1.3429,3.2286,4.5714,1.8000,1.6571,0.4000,10.8571,2010
7,Eulis Stephens,Detroit Mercy,Horz,Sr,137.16,24,34,"Detroit, MI",Wing G,31,31.6,110.2,13.9,51.3,55.91,6.1,10.6,8.4,16.0,33,49,0.673,33,54,0.611,4,22,0.182,1.1,1.7,64.5,0.655344,99.7749,3.8,NaN,1.124976,27.0,40.0,6.0,14.0,0.6750,0.4286,4.0,5.0,0.8000,NaN,99.3834,98.5807,1.30229,70.4798,0.667967,0.23597,0.431997,0.611289,-0.283722,0.895011,13.5484,0.6774,1.2258,1.9032,0.5806,0.3871,0.1290,3.5806,2010
9,Brett Gifford,Albany,AE,Sr,350.52,54,37,NaN,C,30,39.4,79.3,10.1,46.8,46.77,4.4,18.3,7.2,34.5,4,9,0.444,29,61,0.475,0,1,0.000,5.4,1.4,14.5,-1.121340,66.4800,5.0,NaN,0.620668,16.0,21.0,13.0,40.0,0.7619,0.3250,0.0,0.0,NaN,NaN,101.0190,104.1200,1.30440,100.5920,-2.658680,-4.68582,2.027140,-3.827150,-5.133030,1.305880,16.9333,0.6333,2.6667,3.3000,0.6000,0.4000,0.8333,2.0667,2010

In [110]:
# check the combination of team + player name as identifier 
validate_identifier = combined_df.groupby(['player_name','team'])['pid'].nunique().reset_index(name='count').sort_values(by='count', ascending=False)
count_greater_than_1 = validate_identifier[validate_identifier['count'] > 1].shape[0]

total_count = validate_identifier.shape[0]

percentage = (count_greater_than_1 / total_count) * 100
print(f"Percentage of rows with count > 1: {percentage:.2f}%")

Percentage of rows with count > 1: 0.09%

### Get basic player information

In [114]:
player_info = combined_df.groupby(['player_name', 'team']).agg(
    height=('ht', 'max'),  # Maximum height
    min_year=('year', 'min'),  # Minimum year
    max_year=('year', 'max')  # Maximum year
).reset_index()

In [115]:
# last year's position 
last_year_df = combined_df.loc[combined_df.groupby('player_name')['year'].idxmax()]

# Merge the 'pos_class' column from the last year data to the player_info DataFrame
player_info = player_info.merge(last_year_df[['player_name', 'team', 'pos_class']], on=['player_name', 'team'], how='left')

player_info.head()

,player_name,team,height,min_year,max_year,pos_class,type
0,A'Jahni Levias,North Dakota,198.12,2023,2023,Wing G,"Vallejo, CA"
1,A'Torey Everett,Tennessee St.,193.04,2017,2017,Combo G,"Dallas, TX"
2,A'Torri Shine,Grambling St.,198.12,2014,2015,Wing G,NaN
3,A'Uston Calhoun,Bowling Green,200.66,2013,2013,Wing F,NaN
4,A'lahn Sumler,Charleston Southern,193.04,2024,2024,Combo G,"Waterbury, CT"

### Get performance information
- compute weighted average, where weight is Min_per. this is better than using a plain average

In [153]:
combined_df_filtered_v1 = combined_df_filtered.copy()

# # Step 1: Compute weighted values in new columns
# count metrics
combined_df_filtered_v1['weighted_ORtg'] = combined_df_filtered_v1['ORtg'] * combined_df_filtered_v1['Min_per']
combined_df_filtered_v1['weighted_drtg'] = combined_df_filtered_v1['drtg'] * combined_df_filtered_v1['Min_per']
combined_df_filtered_v1['weighted_dporpag'] = combined_df_filtered_v1['dporpag'] * combined_df_filtered_v1['Min_per']
combined_df_filtered_v1['weighted_stops'] = combined_df_filtered_v1['stops'] * combined_df_filtered_v1['Min_per']
combined_df_filtered_v1['weighted_usg'] = combined_df_filtered_v1['usg'] * combined_df_filtered_v1['Min_per']
combined_df_filtered_v1['weighted_eFG'] = combined_df_filtered_v1['eFG'] * combined_df_filtered_v1['Min_per']
combined_df_filtered_v1['weighted_TS_per'] = combined_df_filtered_v1['TS_per'] * combined_df_filtered_v1['Min_per']
combined_df_filtered_v1['weighted_ORB_per'] = combined_df_filtered_v1['ORB_per'] * combined_df_filtered_v1['Min_per']
combined_df_filtered_v1['weighted_DRB_per'] = combined_df_filtered_v1['DRB_per'] * combined_df_filtered_v1['Min_per']
combined_df_filtered_v1['weighted_FTM'] = combined_df_filtered_v1['FTM'] * combined_df_filtered_v1['Min_per']
combined_df_filtered_v1['weighted_FTA'] = combined_df_filtered_v1['FTA'] * combined_df_filtered_v1['Min_per']
combined_df_filtered_v1['weighted_twoPM'] = combined_df_filtered_v1['twoPM'] * combined_df_filtered_v1['Min_per']
combined_df_filtered_v1['weighted_twoPA'] = combined_df_filtered_v1['twoPA'] * combined_df_filtered_v1['Min_per']
combined_df_filtered_v1['weighted_TPM'] = combined_df_filtered_v1['TPM'] * combined_df_filtered_v1['Min_per']
combined_df_filtered_v1['weighted_TPA'] = combined_df_filtered_v1['TPA'] * combined_df_filtered_v1['Min_per']
combined_df_filtered_v1['weighted_twoPM'] = combined_df_filtered_v1['twoPM'] * combined_df_filtered_v1['Min_per']
combined_df_filtered_v1['weighted_twoPA'] = combined_df_filtered_v1['twoPA'] * combined_df_filtered_v1['Min_per']
combined_df_filtered_v1['weighted_blk_per'] = combined_df_filtered_v1['blk_per'] * combined_df_filtered_v1['Min_per']
combined_df_filtered_v1['weighted_stl_per'] = combined_df_filtered_v1['stl_per'] * combined_df_filtered_v1['Min_per']
combined_df_filtered_v1['weighted_pick'] = combined_df_filtered_v1['pick'] * combined_df_filtered_v1['Min_per']
combined_df_filtered_v1['weighted_oreb'] = combined_df_filtered_v1['oreb'] * combined_df_filtered_v1['Min_per']
combined_df_filtered_v1['weighted_dreb'] = combined_df_filtered_v1['dreb'] * combined_df_filtered_v1['Min_per']
combined_df_filtered_v1['weighted_treb'] = combined_df_filtered_v1['treb'] * combined_df_filtered_v1['Min_per']
combined_df_filtered_v1['weighted_ast'] = combined_df_filtered_v1['ast'] * combined_df_filtered_v1['Min_per']
combined_df_filtered_v1['weighted_stl'] = combined_df_filtered_v1['stl'] * combined_df_filtered_v1['Min_per']
combined_df_filtered_v1['weighted_blk'] = combined_df_filtered_v1['blk'] * combined_df_filtered_v1['Min_per']
combined_df_filtered_v1['weighted_pts'] = combined_df_filtered_v1['pts'] * combined_df_filtered_v1['Min_per']


# metrics = [
#     'ORtg', 'usg', 'eFG', 'TS_per', 'ORB_per', 'DRB_per', 'AST_per', 'TO_per',
#     'FT_per', 'twoP_per', 'TP_per', 'blk_per', 'stl_per', 'ftr'
# ]

wa_metrics = combined_df_filtered_v1.groupby(['player_name', 'team']).agg(
    total_min_per=('Min_per', 'sum'),
    avg_offensive_rating=('weighted_ORtg', 'sum'),
    avg_defensive_rating=('weighted_drtg', 'sum'),
    avg_defensive_points_ov_replacement=('weighted_dporpag', 'sum'),
    avg_defensive_stop=('weighted_stops', 'sum'),
    avg_usage_rate=('weighted_usg', 'sum'),
    avg_effective_field_goal_pct=('weighted_eFG', 'sum'),
    avg_shooting_pct=('weighted_TS_per', 'sum'),
    avg_offensive_rebound_pct=('weighted_ORB_per', 'sum'),
    avg_defensive_rebound_pct=('weighted_DRB_per', 'sum'),
    avg_freethrow_made=('weighted_FTM', 'sum'),
    avg_freethrow_attempted=('weighted_FTA', 'sum'),
    avg_2p_made=('weighted_twoPM', 'sum'),
    avg_2p_attempted=('weighted_twoPA', 'sum'),
    avg_3p_made=('weighted_TPM', 'sum'),
    avg_3p_attempted=('weighted_TPA', 'sum'),
    avg_block_pct=('weighted_blk_per', 'sum'),
    avg_steal_pct=('stl_per', 'sum'),
    avg_pick = ('weighted_pick','sum'),
    avg_offensive_reb=('weighted_oreb', 'sum'),
    avg_defensive_reb=('weighted_dreb', 'sum'),
    avg_total_reb=('weighted_treb', 'sum'),
    avg_assists=('weighted_ast', 'sum'),
    avg_steals=('weighted_stl', 'sum'),
    avg_blocks=('weighted_blk', 'sum'),
    avg_points_scored=('weighted_pts', 'sum'),
    
).reset_index()

wa_columns = [col for col in avg_metrics.columns if col not in ['total_min_per', 'player_name', 'team']]

for col in wa_columns:
    wa_metrics[col] /= wa_metrics['total_min_per']

wa_metrics['avg_freethrow_pct']= wa_metrics['avg_freethrow_made']/wa_metrics['avg_freethrow_attempted']
wa_metrics['avg_2p_pct']= wa_metrics['avg_2p_made']/wa_metrics['avg_2p_attempted']
wa_metrics['avg_3p_pct']= wa_metrics['avg_3p_made']/wa_metrics['avg_3p_attempted']

wa_metrics.head()

,player_name,team,total_min_per,avg_offensive_rating,avg_defensive_rating,avg_defensive_points_ov_replacement,avg_defensive_stop,avg_usage_rate,avg_effective_field_goal_pct,avg_shooting_pct,avg_offensive_rebound_pct,avg_defensive_rebound_pct,avg_freethrow_made,avg_freethrow_attempted,avg_2p_made,avg_2p_attempted,avg_3p_made,avg_3p_attempted,avg_block_pct,avg_steal_pct,avg_pick,avg_offensive_reb,avg_defensive_reb,avg_total_reb,avg_assists,avg_steals,avg_blocks,avg_points_scored,avg_freethrow_pct,avg_2p_pct,avg_3p_pct
0,A'Jahni Levias,North Dakota,20.7,90.900000,2289.5442,14.858626,883.1241,19.300000,47.100000,49.610000,4.800000,13.00000,227.7,331.2,331.2,724.5,227.7,703.8,0.00,1.8,0.0,14.66181,28.46250,43.12431,14.66181,8.62569,0.00000,85.38750,0.687500,0.457143,0.323529
1,A'Torey Everett,Tennessee St.,19.0,88.000000,1997.7740,14.797618,577.2371,15.700000,40.500000,50.080000,1.600000,8.10000,342.0,437.0,171.0,570.0,76.0,133.0,11.40,0.3,0.0,2.37500,14.25000,16.62500,13.45770,1.58270,0.79230,45.91730,0.782609,0.300000,0.571429
2,A'Torri Shine,Grambling St.,158.6,94.154098,18477.0218,87.015044,19315.1230,23.094451,45.406936,50.017945,4.008323,10.10971,11400.4,14822.4,13259.6,29519.4,5531.2,17945.0,103.42,2.4,0.0,180.00152,428.27386,608.27538,151.07596,105.84388,34.32940,2066.74504,0.769133,0.449183,0.308231
3,A'Uston Calhoun,Bowling Green,83.8,99.900000,8505.9514,232.791372,13170.6784,25.500000,47.100000,51.500000,7.800000,16.80000,7542.0,9469.4,12989.0,28156.8,1592.2,4525.2,125.70,0.7,0.0,189.94946,399.44946,589.39054,67.04000,30.72946,39.10946,1276.55054,0.796460,0.461310,0.351852
4,A'lahn Sumler,Charleston Southern,73.6,100.700000,8142.3680,161.304704,9459.1456,26.600000,48.000000,50.420000,2.200000,10.10000,3753.6,5225.6,6182.4,13616.0,4195.2,12364.8,73.60,1.9,0.0,43.14432,185.26592,228.41024,119.28352,68.52160,20.30624,1048.16704,0.718310,0.454054,0.339286

### Get plus minus metrics

In [151]:
plus_minus_metrics = combined_df_filtered_v1.groupby(['player_name', 'team']).agg(
    avg_box_plus_minus=('bpm', 'mean'),
    avg_box_offensive_plus_minus=('obpm', 'mean'),
    avg_box_defensive_plus_minus=('dbpm', 'mean'),
    avg_global_plus_minus=('gbpm', 'mean'),
    avg_offensive_global_plus_minus=('ogbpm', 'mean'),
    avg_defensive_global_plus_minus=('dgbpm', 'mean'),
).reset_index()

plus_minus_metrics.head()

,player_name,team,avg_box_plus_minus,avg_box_offensive_plus_minus,avg_box_defensive_plus_minus,avg_global_plus_minus,avg_offensive_global_plus_minus,avg_defensive_global_plus_minus
0,A'Jahni Levias,North Dakota,-5.324950,-2.808850,-2.516100,-3.668870,-2.542440,-1.126440
1,A'Torey Everett,Tennessee St.,-6.374510,-4.922240,-1.452270,-6.502150,-5.713050,-0.789096
2,A'Torri Shine,Grambling St.,-6.934815,-2.114325,-4.820495,-5.110925,-0.919447,-4.191470
3,A'Uston Calhoun,Bowling Green,-3.123610,-1.285750,-1.837860,-1.065030,0.949586,-2.014620
4,A'lahn Sumler,Charleston Southern,-0.456725,0.617211,-1.073940,1.232160,1.533230,-0.301066

### Combine all three df

In [155]:
merged_df = player_info.merge(plus_minus_metrics, on=['player_name', 'team'], how='left')

# Merge the result with wa_metrics
merged_df = merged_df.merge(wa_metrics, on=['player_name', 'team'], how='left')

# Show result
merged_df.to_csv('player_data_college.csv', index=False)